package main

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func main() {
	// Ищем файлы с комментарием //go:embed
	embedFiles := findEmbedFiles(".")

	if len(embedFiles) == 0 {
		fmt.Println("No embed files found")
		return
	}

	// Генерируем код
	if err := generateEmbedCode(embedFiles); err != nil {
		fmt.Printf("Error generating embed code: %v\n", err)
		os.Exit(1)
	}
}

func findEmbedFiles(root string) []string {
	var embedFiles []string

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		// Проверяем только .go файлы
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		// Парсим файл для поиска комментариев //go:embed
		fset := token.NewFileSet()
		node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil // Пропускаем файлы с ошибками парсинга
		}

		// Ищем комментарии //go:embed
		for _, comment := range node.Comments {
			if strings.Contains(comment.Text(), "//go:embed") {
				// Получаем имена встраиваемых файлов из комментария
				lines := strings.Split(comment.Text(), "\n")
				for _, line := range lines {
					if strings.HasPrefix(line, "//go:embed") {
						parts := strings.Fields(line)
						if len(parts) > 1 {
							for _, pattern := range parts[1:] {
								matches, _ := filepath.Glob(pattern)
								embedFiles = append(embedFiles, matches...)
							}
						}
					}
				}
			}
		}

		return nil
	})

	if err != nil {
		fmt.Printf("Error walking directory: %v\n", err)
	}

	return embedFiles
}

func generateEmbedCode(files []string) error {
	// Создаем шаблон
	tmpl := `// Code generated by embed generator. DO NOT EDIT.

package main

import (
	"embed"
)

//go:embed {{range .}}{{.}} {{end}}
var embeddedFiles embed.FS

// GetEmbeddedFile возвращает содержимое встроенного файла
func GetEmbeddedFile(path string) ([]byte, error) {
	return embeddedFiles.ReadFile(path)
}

// ListEmbeddedFiles возвращает список всех встроенных файлов
func ListEmbeddedFiles() ([]string, error) {
	var files []string
	err := fs.WalkDir(embeddedFiles, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}
`

	// Создаем файл
	f, err := os.Create("embed_gen.go")
	if err != nil {
		return err
	}
	defer f.Close()

	// Исполняем шаблон
	t, err := template.New("embed").Parse(tmpl)
	if err != nil {
		return err
	}

	return t.Execute(f, files)
}
