// Code generated by reset tool. DO NOT EDIT.
//go:generate go run ./cmd/reset/main.go .

package router

// Reset сбрасывает состояние URLShortener к начальным значениям.
func (u *URLShortener) Reset() {
	if u == nil {
		return
	}

	if u.DBStorage != nil {
		// Complex pointer type
	}
	u.UseDB = false
	u.FileStoragePath = ""
	u.BaseURL = ""
	u.CookieSecret = u.CookieSecret[:0]
	if u.MemoryStorage != nil {
		*u.MemoryStorage = Storages{}
	}
}

// Reset сбрасывает состояние TestConfig к начальным значениям.
func (t *TestConfig) Reset() {
	if t == nil {
		return
	}

	t.Port = 0
	t.Host = ""
	t.Enabled = false
	t.MaxRequests = 0
	t.Timeout = 0
}

// Reset сбрасывает состояние UserData к начальным значениям.
func (u *UserData) Reset() {
	if u == nil {
		return
	}

	u.ID = ""
	u.Name = ""
	if u.Email != nil {
		*u.Email = ""
	}
	u.Roles = u.Roles[:0]
	clear(u.Settings)
	u.Scores = u.Scores[:0]
	clear(u.Metadata)
}

// Reset сбрасывает состояние ComplexStruct к начальным значениям.
func (c *ComplexStruct) Reset() {
	if c == nil {
		return
	}

	c.Config = TestConfig{}
	c.Users = c.Users[:0]
	clear(c.Cache)
	if c.Counter != nil {
		*c.Counter = 0
	}
	if c.Logger != nil {
		*c.Logger = Logger{}
	}
	if c.parent != nil {
		*c.parent = ComplexStruct{}
	}
}
